### ISSUE TITLE
Nice site!

### ISSUE THREAD

**Issue by wcarhart** [Patrickwalkstar/Web-based-Terminal#1]
Hey Patrick, this is awesome! Have you considered open sourcing this as a JS framework?

I found a small typo on the familiar page: https://github.com/Patrickwalkstar/Patrickwalkstar.github.io/blob/master/pages/familiar.html

Hope things are well!

**Comment by Patrickwalkstar** [comment]
- I have considered doing so, I might need some help though.
- Thanks for catching the typo! I fixed that, made some other updates, and added a summary page. I may need to redo the summary page to make it simple like the terminal page. 
- I still need to work on both the terminal and summary page, and other projects, but progress is progress. 
- I hope things are well for you too!
